### ISSUE TITLE
Create an algorithm that sorts restaurants

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#1]
Create an algorithm that ranks a list of local restaurants taking into account:
- number of violations (ever) and what happened.
- number of violations (within a specific time frame)
- severity of violation
- ding restaurants that fail a follow up inspection

**Comment by qwo** [comment]
I think this would be valuable, but I think it would feel less 'accusatory' if we put this on a perspective by  city, region, neighborhoods etc. Those would be interesting but still allowing people to personally find it out by clicking on a SPECIFIC vendor. 

We talked about this one of the past hacknights

**Comment by qwo** [comment]
#1 and #2 seem like they're very similar

**Comment by qwo** [comment]
wont do
