### ISSUE TITLE
Restaurant Week Filter

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#101]
CSV cleaned up data of all POI on restaurant week.

https://gist.github.com/stanzheng/4fa9147fbb4f02910ec8 

TODO get equivalent json object in OHI app relation ,
http://www.downtownnorfolk.org/enjoy/events/restaurant_week

**Comment by nameispete** [comment]
We used the upcoming event more as an excuse to launch.

I sort of like the idea of having a "special event" icon that automatically brings the user to the center of the event and filters the results to only eateries related to the event, but I think its practical implementation is going to cause more confusion to the user than value. 

I would vote that we nix this idea. We will only have a handful of "restaurant weeks" annually and this feels more like feature creep than a useful addition to the application.

**Comment by qwo** [comment]
+1 agreed. This seems like something that can be mentioned just as an BY THE WAY.. type of deal. "By the way use it for restaurant week when you make a choice" this is already public information

**Comment by qwo** [comment]
bummer. so its wednesday and midway through the week so i'm going to shift gears because it will not be too valuable for much longer. 

Instead we can run with a twitter campaign like 

> Sushi King is a apart of restaurant week. There are 8 violations. See them at OHI/URL #norfolkva #downtownrestaurantweek
