### ISSUE TITLE
Create only one infowindow created for multiple markers

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#105]
see
http://stackoverflow.com/questions/4979401/google-maps-only-one-infowindow-created-for-multiple-markers
http://jsfiddle.net/ifaour/3CvaD/40/

![screenshot 2014-07-05 18 48 36](https://cloud.githubusercontent.com/assets/3683993/3487688/173b2e1c-0497-11e4-9e43-cf739955e7e0.png)

**Comment by nameispete** [comment]
Should this be combined with #51

**Comment by qwo** [comment]
you're right, i thought 'bullets' was referring to entries in the inside the info window. my terminology is confused.
