### ISSUE TITLE
Center the modal submit button

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#115]
Easier to tap the size of the modal by centering it and possibly increasing the size

![screenshot 2014-07-09 22 11 59](https://cloud.githubusercontent.com/assets/3683993/3533723/068fbabc-07d8-11e4-9d16-d16c9d87ce46.png)

**Comment by jalbertbowden** [comment]
.modal-footer button{margin-left:auto; margin-right:auto; display:block}
