### ISSUE TITLE
Focus on text field.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#120]
On click to magnifying glass icon, give focus to text box.

**Comment by jalbertbowden** [comment]
this is easy with css. just as easy with jquery.
i have no clue about the angular syntax though. i can see where the toggle search function is set and being called, but i don't see where the jquery functions are.

**Comment by bschoenfeld** [comment]
Angular encourages you to not use jquery. If you don't need things to run
when the page loads, it should be fine though. I've done it.

**Comment by jalbertbowden** [comment]
ok...but jquery's already on the page...
not arguing, just confused

target the input here, although a better way to do this would be to add a simple class like, search or search-box so you support even more browsers. 
input[type="search"]:hover,input[type="search"]:active,input[type="search"]:focus{outline:1px dotted #000}

**Comment by bschoenfeld** [comment]
Oops. Thought you said jquery wasn't there. My bad. +1 for CSS anyway

**Comment by wbprice** [comment]
addressed in #139
