### ISSUE TITLE
Quick Jump for Cities

### ISSUE THREAD

**Issue by kwarkster** [Code4HR/open-health-inspection-app#126]
There doesn't seem to be an easy way to change your search location- for example, sitting in Norfolk, VA, the app doesn't offer me an easy way to search for restaurants in the Richmond area.  It would be nice to have a space to enter in a zip code rather than have your search anchored in your physical location.

**Comment by qwo** [comment]
changing feature name to city quick jump

**Comment by wbprice** [comment]
I'm thinking pick city name from dropdown, supply zipcode. The interface for this will be tied in with #89.

**Comment by wbprice** [comment]
There's a need to provide an interface for people who refuse geolocation so they can continue to use the app.

**Comment by wbprice** [comment]
Addressed in #157.  Still some room for refinement, but it's working.
