### ISSUE TITLE
Confusing Icons

### ISSUE THREAD

**Issue by kwarkster** [Code4HR/open-health-inspection-app#128]
I wouldn't use a checkmark to signify a corrected violation.  A checkmark alone, to me at least, signifies "non issue," or "good inspection," not a corrected violation.  I would rethink the key/representation of violations.  Maybe create two symbols for violations- one for critical, one for non critical.  A corrected violation might be a non-critical violation symbol with a checkmark overlay. Finally, a single checkmark signifies no violations/clean bill.

**Comment by qwo** [comment]
related to #129 for changing the icon to more intuitive meanings
