### ISSUE TITLE
Icon Key Idea

### ISSUE THREAD

**Issue by kwarkster** [Code4HR/open-health-inspection-app#129]
Rather than having to scroll back to the top of the page to remember what the icons signify, it'd be nice to have alt-text pop up to remind me what they mean.

**Comment by wbprice** [comment]
This should already be happening.  Was it not working for you last night? 
![screen shot 2014-07-17 at 11 14 52 am](https://cloud.githubusercontent.com/assets/2590422/3615072/32bffd52-0dc5-11e4-941c-a6b18c4ae7cf.png)

**Comment by qwo** [comment]
so an on hover alt text was available? thats great. is this on the about modal or should it be?

did you find the alt text helpful @kwarkster? I also am interested how this behaves on mobile.

**Comment by kwarkster** [comment]
Yeah- the alt-text is super helpful! It's working for me now- I was just impatient before.  Is there anyway to make it pop up faster than w/in 3+secs?

**Comment by jalbertbowden** [comment]
thats not going to work on mobile, ie where there is no :hover

**Comment by qwo** [comment]
agreed if there a mobile oh hover solution, or make it an on:click event to get a tiny popup tooltip like we got before that would also be useful.

**Comment by wbprice** [comment]
Longpress is pretty common in native apps.  We can implement this in vanilla JS:
http://stackoverflow.com/questions/2625210/long-press-in-javascript

**Comment by jalbertbowden** [comment]
you can target non touch ua via: 
if (!("ontouchstart" in document.documentElement)) {
    document.documentElement.className += " no-touch";
}
and just add .no-touch to the style sheet

also......isn't vanilla JS........just JS?
;)

**Comment by wbprice** [comment]
What if the green were instead a yellow (ochre or something).  I'd read that less as a solid "pass" and more as "caution", which is probably closer to what we're looking for anyway.

**Comment by kwarkster** [comment]
That sounds like a solid idea to me.

**Comment by wbprice** [comment]
Reference for Angular longpress. https://gist.github.com/BobNisco/9885852

**Comment by wbprice** [comment]
Partially addressed by #159.  Corrected during inspection is now yellow.  Still looking into longpress.  It's less common on mobile web so might not do it after all.
