### ISSUE TITLE
Implement Grunt

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#13]
How comfortable is everyone with Grunt and Node?  Don't want to make it too hard to contribute to this if I can avoid it.

**Comment by jalbertbowden** [comment]
i'm not up to speed on grunt, but if its necessary, its necessary.
why is it needed?

On Mon, Feb 24, 2014 at 11:26 AM, William Blaine Price <
notifications@github.com> wrote:

> How comfortable is everyone with Grunt and Node? Don't want to make it too
> hard to contribute to this if I can avoid it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/open-health-inspection-app/issues/13
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by wbprice** [comment]
There are a lot of tasks that can help us optimize performance when we deploy (css/js concatenation/minification, lossless image optimization, etc).  Angular and Bootstrap are being delivered by CDN in minified state, this would handle the rest of it.

**Comment by BretFisher** [comment]
I'm good with Grunt, so just document the config file inline.  I think Node
is easier for us to deal with cross platform then just about any other web
platform out there (ruby, python, c#, java, go, etc.), so I'm a fan :)

**Comment by wbprice** [comment]
Chris Coyier has a great article on Grunt here: http://24ways.org/2013/grunt-is-not-weird-and-hard/ and I'd be happy to run the 15-20 minute Grunt workshop as needed.

**Comment by jalbertbowden** [comment]
lol....i'm aware of its purposes. grunts creator and i talk ever so often.
i was asking specifically but i guess that's the same thing

On Mon, Feb 24, 2014 at 11:52 AM, William Blaine Price <
notifications@github.com> wrote:

> Chris Coyier has a great article on Grunt here:
> http://24ways.org/2013/grunt-is-not-weird-and-hard/ and I'd be happy to
> run the 15-20 minute Grunt workshop as needed.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/open-health-inspection-app/issues/13#issuecomment-35907268
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by wbprice** [comment]
It looks like there are some issues with minification and Angular's dependency injection (nothing that can't be worked around, http://docs.angularjs.org/tutorial/step_05) but we'll want to keep it in mind if we implement grunt.

**Comment by jalbertbowden** [comment]
so you're using angular...
not worried about seo?
showing content if js fails/is not available?

On Monday, February 24, 2014, William Blaine Price notifications@github.com
wrote:

> It looks like there are some issues with minification and Angular's
> dependency injection (nothing that can't be worked around,
> http://docs.angularjs.org/tutorial/step_05) but we'll want to keep it in
> mind if we implement grunt.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/open-health-inspection-app/issues/13#issuecomment-35925042
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by wbprice** [comment]
Open source provides: [grunt-html-snapshot](https://github.com/cburgdorf/grunt-html-snapshot).
Per [this article](http://www.ng-newsletter.com/posts/serious-angular-seo.html), should handle the SEO issue.  As for people who have javascript disabled... dunno.  We'd have to figure out a fallback.  At the very least, could generate a list of the worst local offenders daily and serve that as a static page if anything goes south.

**Comment by jalbertbowden** [comment]
those may not even b issues, just spitballing thoughts.
if you are only using js, and its off, you cant render anything...need
another lang

again could not be a issue

On Monday, February 24, 2014, William Blaine Price notifications@github.com
wrote:

> Open source provides: grunt-html-snapshothttps://github.com/cburgdorf/grunt-html-snapshot
> .
> Per this articlehttp://www.ng-newsletter.com/posts/serious-angular-seo.html,
> should handle the SEO issue. As for people who have javascript disabled...
> dunno. We'd have to figure out a fallback. At the very least, could
> generate a list of the worst local offenders daily and serve that as a
> static page if anything goes south.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/open-health-inspection-app/issues/13#issuecomment-35951289
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/
