### ISSUE TITLE
"About" Info

### ISSUE THREAD

**Issue by kwarkster** [Code4HR/open-health-inspection-app#132]
It looks like the "open health inspection" icon is hyperlinked, but nothing happens when I click on it.  It'd be cool to let this serve as a link to the info you see when you first enter the page- instructions on how to use the app, info about the brigade, maybe some kind of mission statement for the app, etc.

**Comment by qwo** [comment]
Hi,

I think traditionally the experience is to use this as a way to jump to the "home" of the application or go back to the original screen.

This performs as normal but if you think there is better notation we could add or link in the introduction modal let us know!
