### ISSUE TITLE
Marker in the Zone 

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#134]
Person marker in the middle makes the user experience is not too good.

A person makes user think that its a streetview marker and is not easy to recognize.

Similar to uber and lyft they have a pin in the middle. We should investigate removing it or changing it to a different icon like a pin.

**Comment by jalbertbowden** [comment]
wow. nicely said.

but i do concur, it looks more like a feature to me...why not just make it a separate color from the marker pins....or better yet add some shadow or a little circle around the pin

**Comment by qwo** [comment]
two thoughts on this.

This was user feedback from some brigade people at hacknight. @aimsrandom and katilyn were doing some usability studies and added a great amount of feedback on the issue tracker.

The idea of the marker is because its a UX mechanic borrowed from Lyft/Sidecar where you move your map and center it around your interest point and then hit "GO". We had to solve the problem of helping the user find the center since open health inspection finds the results in a circle from the center of the map.

Also its being created as an actual marker point right now but we think the experience would be better if it was an absolute CSS element centered in the device screen since the marker has to be redrawn on drag.
