### ISSUE TITLE
Tweet this restaurants results

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#137]
by clicking a button on the restaurants inspection report.

**Comment by qwo** [comment]
+1 for this idea. Share the data. By proxy.
- LOOK AT THIS INSPECTION I FOUND.  {{Link}}
- What does this violation mean {{link}} 
- Yes my restaurant is always ontop of our inspections {{link}}

**Comment by qwo** [comment]
i thought we might of been going with "share with" buttons for twitter and not an account although we could do "share with via @openhealthva" handle

**Comment by wbprice** [comment]
I'm moving quickly and breaking things this morning.  I thought it was necessary to create an account to set up the cards, and it looks like it's not.  If the account isn't needed for this issue, I'll delete the account.

**Comment by qwo** [comment]
LOL i mean keep it, i mean setting up twitter accounts is a pain the ass worse thing is it just sits aorund

**Comment by wbprice** [comment]
Sidebar, internet at Panera is terrible this morning.

**Comment by qwo** [comment]
Which Panera? Aren't they always terrible. Free wifi always has it price, usually mental anguish.

**Comment by wbprice** [comment]
Town Center.  Closed a bunch of issues over a bagel and some coffee, so can't complain too much.

**Comment by wbprice** [comment]
![screenshot from 2014-07-31 07 56 57](https://cloud.githubusercontent.com/assets/2590422/3763904/df84fa76-18a9-11e4-82e5-be59a3166383.png)
Progress on this.

**Comment by kmcurry** [comment]
"worse thing is it just sits aorund"

That's actually a pretty bad thing.

On Sun, Jul 20, 2014 at 10:13 AM, Stanley Zheng notifications@github.com
wrote:

> LOL i mean keep it, i mean setting up twitter accounts is a pain the ass
> worse thing is it just sits aorund
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/137#issuecomment-49547440
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by kmcurry** [comment]
:thumbsup:

On Thu, Jul 31, 2014 at 7:57 AM, W. Blaine Price notifications@github.com
wrote:

> [image: screenshot from 2014-07-31 07 56 57]
> https://cloud.githubusercontent.com/assets/2590422/3763904/df84fa76-18a9-11e4-82e5-be59a3166383.png
> Progress on this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/137#issuecomment-50748943
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by wbprice** [comment]
Peter had a cool idea last night related to using the account: tweet links to the reports of restaurants every so often.

**Comment by wbprice** [comment]
Original issue addressed in #151
