### ISSUE TITLE
Complete wireframe

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#14]
working with @cosmicmeow to get the various views roughed out.

**Comment by wbprice** [comment]
@cosmicmeow List view and map view are really the same view, so one less thing to mock up.  Restaurant view is similar to list/map view, but displays different information?

**Comment by qwo** [comment]
@RainmakerLegendz created some wireframes that were added on this pull>

https://github.com/c4hrva/open-health-inspection-app/commit/400a36fdfa0284f8e7d491eda2064167ba47c153

also some other branding and identity stuff. I dont think we're at that stage right now with the app but  wanted to make sure someone saw this.

**Comment by wbprice** [comment]
I'm digging what @RainmakerLegendz put up, but haven't built the live version just yet.  Also, aside from vague ideas on my part, we don't really have desktop wireframes.  I'll upload some of my ideas later, but definitely looking for input here.
