### ISSUE TITLE
Icon hex colors

### ISSUE THREAD

**Issue by aimsrandom** [Code4HR/open-health-inspection-app#140]
Repeat & Critical:
background: #f18775
color: #cf2f36

Fixed during inspection:
background: #8dcc8d
color: #3c9542

![ohi_icon_colors_screenshot](https://cloud.githubusercontent.com/assets/7144451/3635516/7aec83d4-0f78-11e4-8290-e5c63fe01d3a.png)

**Comment by wbprice** [comment]
resolved in #142
