### ISSUE TITLE
Previews on Social Media

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#144]
![screenshot 2014-07-19 16 48 11](https://cloud.githubusercontent.com/assets/3683993/3635703/0dc93ca8-0f86-11e4-8343-fc84d4bc6901.png)

Add meta tags so social networks can have previews.
https://dev.twitter.com/docs/cards
http://davidwalsh.name/facebook-meta-tags

**Comment by wbprice** [comment]
Already set up for Facebook.  Created and submitted dev card for Twitter (pending approval) in #148
