### ISSUE TITLE
Logo - replace spoon with fork.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#152]
At the advice of people (like Noel) who do design for a living.

**Comment by wbprice** [comment]
Proposed new logos:
![logo-big](https://cloud.githubusercontent.com/assets/2590422/3871038/824d21cc-20eb-11e4-8772-48f5181e4e23.png)
![logo](https://cloud.githubusercontent.com/assets/2590422/3871039/82575d9a-20eb-11e4-9abe-106d8aadf9ae.png)

**Comment by jalbertbowden** [comment]
looks good dude

**Comment by wbprice** [comment]
Addressed in #158
