### ISSUE TITLE
Kitttttyyyyyyyyyyy

### ISSUE THREAD

**Issue by aimsrandom** [Code4HR/open-health-inspection-app#153]
![cat_inspector_v2](https://cloud.githubusercontent.com/assets/7144451/3835983/03d00568-1dca-11e4-83a5-49334a0ff95b.png)

**Comment by wbprice** [comment]
:thumbsup:

**Comment by ghost** [comment]
[This](https://xkcd.com/231/).

**Comment by ghost** [comment]
Also, welcome to the Scottish fold, Purrlock!

**Comment by kmcurry** [comment]
YES! YES! YES!

On Wed, Aug 6, 2014 at 8:50 PM, Ryan Y. notifications@github.com wrote:

> Also, welcome to the Scottish fold, Purrlock!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/153#issuecomment-51417580
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by qwo** [comment]
Very cool

**Comment by wbprice** [comment]
Addressed in #155
