### ISSUE TITLE
Define the purpose/goals of the app.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#16]

**Comment by wbprice** [comment]
moved from another thread: @mullerj
Problem:
I want to find out if a restaurant is safe

• See restaurants that are close by
• See quick view of health safety of a restaurant
• See restaurants by cuisine
• Search for a specific restaurant
• See inspection/violation details for a restaurant

**Comment by qwo** [comment]
a lot of the traction is going towards a consumer based app, but I think also exposing the data and exposing easy points for businesses & Virginia health to keep up with would be useful 

from a business perspective.
-Be able to keep up with their own businesses
-Make sure their restaurants are correctly depicted

Health department
- Allow them to see which restaurant is coming due
- Allow them to directly link reports
