### ISSUE TITLE
Inspections not listing in date order

### ISSUE THREAD

**Issue by ttavenner** [Code4HR/open-health-inspection-app#166]
I just noticed inspections don't like in order of date. I think this might be because the API is returning the date as a string, but you can let me know.

**Comment by wbprice** [comment]
As far as I know, the front-end isn't doing anything to sort the inspections by date, it's just displaying the data in the order returned by the API call.

**Comment by wbprice** [comment]
@ttavenner I haven't seen this happen in the wild.  Did you change the API?

**Comment by ttavenner** [comment]
No. Check out Happy Family: http://openhealthinspection.com/#/vendor/happy-family-restaurant-3050-clinch-street

Scroll down past 30-Aug-2012.

**Comment by wbprice** [comment]
That restaurant is so toxic that it's causing data quality issues?

**Comment by ttavenner** [comment]
Fixed in #266
