### ISSUE TITLE
Improve Search: Ignore Punctuation

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/open-health-inspection-app#177]
Searching for `Jimmy Johns` returns completely different results than searching for `Jimmy John's`

**Comment by ttavenner** [comment]
This is something that would need to be implemented in the API. We probably need to create a search string or slugify the search query and search the slugs used for the URL.

**Comment by ttavenner** [comment]
This was addressed by [Code4HR/open-health-inspection-scraper@a3874637](https://github.com/Code4HR/open-health-inspection-scraper/commit/a38746375cf4ed22497c312e6aed11276e8f1bf0) and [Code4HR/open-health-inspection-api@327e711](https://github.com/Code4HR/open-health-inspection-api/commit/327e7112986613d56179913778655b6105c13ce0)
