### ISSUE TITLE
Score is interpreted as an official score

### ISSUE THREAD

**Issue by aimsrandom** [Code4HR/open-health-inspection-app#182]
In the score, perhaps replace "Overall Rating" with "Our Score"

screenshot:

![ohi-score-update](https://cloud.githubusercontent.com/assets/7144451/4227596/c767ebfa-3948-11e4-85d8-51711bf9b3f3.jpg)

**Comment by kmcurry** [comment]
:thumbsup: smart suggestion

On Wed, Sep 10, 2014 at 8:15 PM, aimsrandom notifications@github.com
wrote:

> In the score, perhaps replace "Overall Rating" with "Our Score"
> 
> screenshot:
> 
> [image: ohi-score-update]
> https://cloud.githubusercontent.com/assets/7144451/4227596/c767ebfa-3948-11e4-85d8-51711bf9b3f3.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/182.

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by wbprice** [comment]
addressed in #187
