### ISSUE TITLE
Upon first visit, the map can take a while to load

### ISSUE THREAD

**Issue by aimsrandom** [Code4HR/open-health-inspection-app#184]
From usability testing, when the user first visited the site, the map was taking a while to load, but the user wasn't aware of that.  He just started clicking around on the icons.

Perhaps show a loading icon or bar while the map is loading?

**Comment by kmcurry** [comment]
The more I use it the less I want the map.

When I open the app I want to look up a restaurant.

"We're thinking about going to Kanpai or Matsu for sushi. Let's look those up on OHI."

**Comment by wbprice** [comment]
@kmcurry It would certainly improve performance not to use the map on mobile.

**Comment by wbprice** [comment]
@aimsrandom can you start thinking about what the app would look like if we were to remove the map altogether?

**Comment by aimsrandom** [comment]
@wbprice sure thing, I'll have something for us to collaborate on next wednesday

**Comment by wbprice** [comment]
Addressed in #207 by removing the map.
