### ISSUE TITLE
Desktop View for Restaurant Listings 

### ISSUE THREAD

**Issue by aimsrandom** [Code4HR/open-health-inspection-app#193]
![ohi_desktop_home](https://cloud.githubusercontent.com/assets/7144451/4547548/120733a4-4e4e-11e4-9d27-f77cbbca9dbe.png)

The rating colors here are okay (the green, red, and mustardy yellow) - I suggest using the hex values for the ones you currently use for scores.

For the "View More" arrow icon, I believe you can pull that from the font icon repository you're using now.

I think the only scenario I'm missing is if the restaurant does not have any inspection reports - correct?

**Comment by wbprice** [comment]
<3

**Comment by wbprice** [comment]
Addressed in #207
