### ISSUE TITLE
Vendors with no inspections don't have a card

### ISSUE THREAD

**Issue by ttavenner** [Code4HR/open-health-inspection-app#195]
See for instance O'Connor's: http://openhealthinspection.com/#/vendor/oconnor-brewing-co-211-w-24th-st

The close button [x] shows up but nothing else. I get the same results in several different browsers and in mobile.

**Comment by wbprice** [comment]
In that specific instance, the API is returning a 500 error.  http://api.openhealthinspection.com/inspections?vendorid=oconnor-brewing-co-211-w-24th-st

**Comment by ttavenner** [comment]
Huh, though I had checked that, but this one is one my side.
