### ISSUE TITLE
Fixer Upper for Purrlock

### ISSUE THREAD

**Issue by aimsrandom** [Code4HR/open-health-inspection-app#208]
So, Purrlock's white border needed some cleaning up (see http://puu.sh/cF06n/32115be087.jpg).  Attached is the cleaned up version.

Also, @ttavenner had an amazing idea to give him a talk bubble that says, "O HI".  That's the next phase of this graphic.

![cat_inspector](https://cloud.githubusercontent.com/assets/7144451/4929690/dc22e628-6556-11e4-813b-43faea8ecd32.png)

**Comment by wbprice** [comment]
lol, sounds good.

**Comment by wbprice** [comment]
@aimsrandom I don't have a Photoshop license handy and I'm rubbish with GIMP.  Can I delegate making a new social media splash image to you?

**Comment by wbprice** [comment]
addressed in #227
