### ISSUE TITLE
Geofencing broken, reoccuring popups

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#209]
geolocation to location outside of VA geofencing breaks app. There is an alert somewhere that keeps running until it finds results.

`alert(" no restaurants within ... xxx" expanding search")`
repeats multiple times.

**Comment by qwo** [comment]
IN Within undefined mi.

**Comment by wbprice** [comment]
Gross. I think adding unit testing will help prevent this kind of regression in the future.

**Comment by qwo** [comment]
i mean just ctr + f for 'alert' and remove that in a loop.

On Fri, Nov 14, 2014 at 6:44 AM, W. Blaine Price notifications@github.com
wrote:

> Gross. I think adding unit testing will help prevent this kind of
> regression in the future.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Code4HR/open-health-inspection-app/issues/209#issuecomment-63073434
> .

## 

Stanley Zheng

**Comment by ghost** [comment]
@wbprice: :+1:

**Comment by ghost** [comment]
Looks like #210 and #211 corrected this.

**Comment by wbprice** [comment]
Not really.  We could remove the alert to match the behavior of the name search function.  I tested this in Richmond over the weekend and it was a little annoying.

**Comment by wbprice** [comment]
Fixed in #215.
