### ISSUE TITLE
JSON files from database break Angular

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#23]
The first couple of lines in the JSON for a given restuarant include something like: 

"_id" : ObjectId("530907537d95393b690c216d"),

Looks like this is a function in a JSON, which doesn't validate.   Deleting this line causes everything to work again.  Not an ideal solution because this line serves as a good unique ID.  Find some way to sanitize this input in API or in front-end?

**Comment by BretFisher** [comment]
that's mongodb standard document ID that gets added on insert. It should stay there for proper db function.

**Comment by wbprice** [comment]
Is this something that should be filtered out by the API when it serves JSON to the front-end?

**Comment by ttavenner** [comment]
These will be the ids you will reference for requesting specific documents. They shouldn't be served to the end user though.

**Comment by ttavenner** [comment]
For the API, the frontend should pass these as strings which will be converted by the API to objectids for the purposes of interfacing with Mongo.

**Comment by ttavenner** [comment]
At least that's what I think right now while the API is purely a pipe dream.

**Comment by wbprice** [comment]
Sounds good.  I want to keep what I'm doing right now somewhat grounded in reality, so I'll just assume that I'm working with strings for the time being.

**Comment by bschoenfeld** [comment]
> Is this something that should be filtered out by the API when it serves JSON to the front-end?

Yes. The server will convert the GUID to a string before sending it through the API.

**Comment by wbprice** [comment]
Yup, this is what's happening now that my local copy is pulling from the API.
