### ISSUE TITLE
iOS - Visiting a restaurants detail page redirects to the home page.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#252]
Reported by @bschoenfeld and replicated in iOS simulator.

Visiting this in Simulator...

```
http://openhealthinspection.com/#/vendor/handsome-biscuit-2511-colonial 
```

...causes the browser to redirect to the home route.

**Comment by bschoenfeld** [comment]
I got this on Safari too.

![ohi-bug](https://cloud.githubusercontent.com/assets/565347/7120436/34ae489a-e1db-11e4-9c83-f2357e68b40c.gif)

**Comment by wbprice** [comment]
@bschoenfeld are you able to replicate here?

```
http://next.openhealthinspection.com/#/vendor/handsome-biscuit-2511-colonial
```
