### ISSUE TITLE
GPS search doesn't work

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/open-health-inspection-app#269]
When I'm at a restaurant and I want to check it's score I need to use GPS search my mobile. When I click the GPS button nothing happens. I tried Safari and Chrome on iPhone

**Comment by qwo** [comment]
Strange I just tested on Nexus 6p and chrome just now hmm anyone else
confirm?

**Comment by qwo** [comment]
I just tested on iPhone 5s also did you hit now allow?

**Comment by kmcurry** [comment]
This is working for me, too. Delay on results and I didn't realize it was doing something.
