### ISSUE TITLE
Update my location after permitting geolocation

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#33]
Geolocation is working(-ish) right now.  On first load, browser asks for permission to geolocate, but after permission is granted the map center doesn't update automagically.   I'm working on watching for permission to be granted and then updating map center.

**platforms where geolocation doesn't work yet**
- Firefox - Linux
- Firefox - Old versions of Mac OS
- Safari - Old versions of Mac OS

In all cases, the browser prompts users for permission to grab location, but map doesn't update afterwards.

**Comment by kmcurry** [comment]
:thumbsup:

**Comment by wbprice** [comment]
being addressed in #41, but need to do more testing.
