### ISSUE TITLE
Create a way to store favorite restaurants.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#4]

**Comment by qwo** [comment]
ah this is an old issue, storing favorite restaurants, that'll require a persistent layers and user auth.

Channeling my inner googleIO Do you think the technical complexity vs value is worth it?

**Comment by wbprice** [comment]
I don't think this would add a lot of value.  It was more of a "how can we apply the lessons of hrt.bus here?" thought.
