### ISSUE TITLE
View Cut off in Mobile

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#47]
![photo1](https://cloud.githubusercontent.com/assets/3683993/2928212/2453b588-d779-11e3-8db1-808a9c836537.jpg) {width: 100px; height:300px}
iPhone 5 Chrome. 

View is partially cut off

**Comment by wbprice** [comment]
This is because the API changed and I haven't had the time or energy to update the app yet.  I'll take care of it (and the title text wrapping) soon.

**Comment by qwo** [comment]
on a site note that image is huge lemme resize it down. I will took a peer around Angular too :)

**Comment by wbprice** [comment]
This was addressed in #49 (and a quick change to main repo afterwards).
