### ISSUE TITLE
Search button doesn't work in iPhone 4S/Safari

### ISSUE THREAD

**Issue by ttavenner** [Code4HR/open-health-inspection-app#60]
Clicking the button does not bring up the search bar. Everything else functions as intended.

**Comment by wbprice** [comment]
Kind of game breaking, so I'll see about knocking this out over lunch.

**Comment by bschoenfeld** [comment]
Reproduced on iPhone 5 in Chrome and Safari.

**Comment by wbprice** [comment]
It doesn't work on Desktop Safari either.

**Comment by wbprice** [comment]
Original reference is here: http://tympanus.net/codrops/2013/06/26/expanding-search-bar-deconstructed/ Working on fix now.

**Comment by wbprice** [comment]
Well, current input isn't as flashy but it works. Maybe replace later.
