### ISSUE TITLE
README needs instructions on installing 3rd party libs

### ISSUE THREAD

**Issue by bschoenfeld** [Code4HR/open-health-inspection-app#61]
I'm not sure how to use these fancy tools to get Angular and Underscore on my local build

**Comment by wbprice** [comment]
AngularJS/Bootstrap are being served by CDN and the calls for that are in index.html.  At the moment I'm just using grunt to minify/concatenate CSS and JS, which is described in the readme.

**Comment by bschoenfeld** [comment]
Hmm. How are you running locally? Do you have a node server or something? If you just load index.html into the browser window, you get these errors:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND file://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js
Failed to load resource: net::ERR_FILE_NOT_FOUND file://ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular-route.min.js
Failed to load resource: net::ERR_FILE_NOT_FOUND file://ajax.googleapis.com/ajax/libs/angularjs/1.2.9/angular-animate.min.js
Failed to load resource: net::ERR_FILE_NOT_FOUND file://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js
Failed to load resource: net::ERR_FILE_NOT_FOUND file://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular.min.js
Failed to load resource: net::ERR_FILE_NOT_FOUND file://ajax.googleapis.com/ajax/libs/angularjs/1.2.12/angular-resource.min.js
Uncaught ReferenceError: angular is not defined production.js:7
Uncaught ReferenceError: _ is not defined angular-google-maps.min.js:5
```

**Comment by qwo** [comment]
are you using the command grunt serve 
 **\* oops. this doesn't work. (im being a dummy) listen to blaine :) I haven't touched this project in a bit.

**Comment by wbprice** [comment]
I didn't know about grunt serve when I set up the project.  I'm running the project using MAMP on my laptop, but any localhost type thing will do.

**Comment by bschoenfeld** [comment]
I'm using grunt watch because the README told me to. Whatever the process, it should be added to the README. I suggest we recommend something specific.

**Comment by wbprice** [comment]
Sounds good.  I like the idea of using grunt serve to simplify this process too.

**Comment by qwo** [comment]
I created a pull, these instructions should be more stream lined.

https://github.com/c4hrva/open-health-inspection-app/pull/63
