### ISSUE TITLE
Add metadata description

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/open-health-inspection-app#64]
The metadata description is super important for social media and SEO. It's how previews show your tag line. Add a snazzy tag line to our metadata description
![screen shot 2014-06-05 at 10 34 32 am](https://cloud.githubusercontent.com/assets/69151/3188863/aa51d05c-ecbe-11e3-8818-85bf8fbe1463.png)

**Comment by qwo** [comment]
The pains of angularjs. We would have to build a static wrapper around the site, maybe including the welcome, instructions, and how to use the site.

**Comment by wbprice** [comment]
I added a meta description to index.html.  Wouldn't that work?

**Comment by kmcurry** [comment]
Yes. I just submitted a pull request for index.html but it can't be automagically merged

**Comment by wbprice** [comment]
My bad.  I jumped the gun and edited main repo directly.  Will merge your changes over lunch.

**Comment by kmcurry** [comment]
Bad civic hacker. No cookie.

**Comment by wbprice** [comment]
We can make this better with a thumbnail/screenshot of the app for social media.  https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fopenhealthinspection.com

**Comment by kmcurry** [comment]
:thumbsup:

**Comment by wbprice** [comment]
donesies.
