### ISSUE TITLE
There don't seem to be many results near me

### ISSUE THREAD

**Issue by kmcurry** [Code4HR/open-health-inspection-app#68]
Tried Chrome and Safari multiple times:

![screen shot 2014-06-05 at 9 59 39 pm](https://cloud.githubusercontent.com/assets/69151/3195942/4aec1c02-ed1e-11e3-80e3-c6dc29296f58.png)

**Comment by wbprice** [comment]
At the moment there's not a way to say "Give me restaurants within x miles away, so the distance was hardcoded to 500 meters.  I'm going to look at expanding the search radius as the screen moves or until a good number of search results are displayed.

**Comment by qwo** [comment]
maybe instead of search radius, number of results?

Can the App zoom to fit the number of Points-Of-Interest or is it the same
zoom level

On Thu, Jun 5, 2014 at 10:07 PM, W. Blaine Price notifications@github.com
wrote:

> At the moment there's not a way to say "Give me restaurants within x miles
> away, so the distance was hardcoded to 500 meters. I'm going to look at
> expanding the search radius as the screen moves or until a good number of
> search results are displayed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/68#issuecomment-45296218
> .
> 
> ---
> 
> Spam
> https://www.spamtrap.odu.edu/canit/b.php?i=01MaO7JMp&m=6c8eb34d98ec&t=20140605&c=s
> Not spam
> https://www.spamtrap.odu.edu/canit/b.php?i=01MaO7JMp&m=6c8eb34d98ec&t=20140605&c=n
> Forget previous vote
> https://www.spamtrap.odu.edu/canit/b.php?i=01MaO7JMp&m=6c8eb34d98ec&t=20140605&c=f

## 

Stanley Zheng
@stanzheng http://twitter.com/stanzheng

**Comment by wbprice** [comment]
The reason I had limited the distance initially was because of the performance hit of drawing a bunch of markers at once.  Would be interesting to see what other approaches there are to minimizing the performance hit.  Example, could make a much larger geosearch call but only render markers in a given radius, and then render the rest when the map center moves closer.

Also yes. http://angular-google-maps.org/api#google-map

**Comment by qwo** [comment]
if there is a query parameter for mongo for the distance for geospatial distance, let the zoo level be a multiplier maybe for how far we're search.

I know its capped by # of results and distance but maybe we could do something of the sort of.

Default zoom level 10, 1000 meters, cap 25 results

If zoom in to 11, x by 1.25 for each zoom out and do a linear increase. These numbers are just guestimations but updating geospatial index query number to solve for large suburban areas?

**Comment by wbprice** [comment]
See also: driving down I264 at 60mph.

**Comment by qwo** [comment]
uh. dangerous edge case. no fix :)

**Comment by wbprice** [comment]
Addressed in #207
