### ISSUE TITLE
.gitignore file should be present?

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#69]
should ignore node_modules at least :)?

**Comment by qwo** [comment]
Where are the dependencies saved?

https://www.npmjs.org/doc/faq.html#Should-I-check-my-node_modules-folder-into-git @wbprice

**Comment by wbprice** [comment]
Nothing in node_modules needs to go up on the live site, it's just for minifiying/concatenating files locally.  Safe to ignore node_modules for the purposes of git.
