### ISSUE TITLE
xbrowsercompat

### ISSUE THREAD

**Issue by jalbertbowden** [Code4HR/open-health-inspection-app#73]
firefox and chrome in win7 are off on the index page;
the search box in ff is below the header;
in chrome you can see a pixel line of light color, right before header ends. not sure if that one is on purpose...
also the maps are zoomed differently: chrome zoom seems perfect, ff zoomed too far in.

**Comment by qwo** [comment]
@jalbertbowden could you check these again and if these issues still persist? I think we're all mac-aholics here.

**Comment by nameispete** [comment]
This can be closed. Tested chrome and firefox in Windows 7 and windows 8. Everything looks consistent.

**Comment by qwo** [comment]
Thats what I thought too @nameispete but i just checked and the issue remains. 

See -> Firefox Latest, underneath the search bar the white rectangle space goes outside the bounds. This is definitely a remaining CSS issue that only happens on firefox. 

It is low priority and so much so  :) people like you and I ourselves miss it but this is something someone with more CSS fu can fix.
![screenshot 2014-07-11 13 30 11](https://cloud.githubusercontent.com/assets/3683993/3556201/22d957ce-0921-11e4-8f7a-e27c1d0ab306.png)

**Comment by nameispete** [comment]
Oh-- you are right. I did not see that. My bad.

**Comment by qwo** [comment]
you're totally fine, i actually said i wanted to close it until blaine pointed it out. its really easy to miss

**Comment by jalbertbowden** [comment]
you'd have to define these prior i reckon, but in my world, opera and ie have to pass to get cross-browser compat....naturally need to define which versions of ie, etc.

**Comment by ghost** [comment]
Pass it with links.

Oh wait.  :cry:

**Comment by wbprice** [comment]
That specific issue has been resolved recently.
