### ISSUE TITLE
Marker Clustering for Dense or Zoomed out Views

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#74]
https://developers.google.com/maps/articles/toomanymarkers#viewportmarkermanagement
![screen shot 2014-06-08 at 11 26 37 pm](https://cloud.githubusercontent.com/assets/3683993/3213232/e9ca8e8a-ef85-11e3-902f-766ec630e388.png)

**Comment by wbprice** [comment]
+1

**Comment by wbprice** [comment]
The maps library I'm using handles this! hooray! I'll work on this when I'm better rested.

**Comment by nameispete** [comment]
As discussed last night, we can address this in user education.

**Comment by qwo** [comment]
+1 wbprice realized its not a drop in replacement so it'll have to come in a bit later

Nice to see you on @nameispete
