### ISSUE TITLE
Identity: Logo, icons, etc.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#77]

**Comment by qwo** [comment]
@RainmakerLegendz @TheWhiteKyle @cosmicmeow @aureately

Any thoughts on this?
http://openhealthinspection.com/#/

**Comment by qwo** [comment]
@aureately  we are talking logos. can you help out on this?

## Brain Dump,
- Food Plate
- Magnifying glass
- Food plate that is a magnifying glass, with the handle being a fork and knife. 
- transparent food? 
- something cool

Brand/Logo should be friendly for social media, icons for apps, etc. in relation to https://github.com/c4hrva/open-health-inspection-app/issues/77

**Comment by nameispete** [comment]
I think we have to identify the brand. OHI. Like the idea of OHI on a plate. 

For icons, a fork and knife, in place of pins would be nice as well.

**Comment by nameispete** [comment]
Concept? 

![stock-vector-plate-with-cutlery-127307942](https://cloud.githubusercontent.com/assets/6691372/3478291/a80cd7fc-0333-11e4-8e32-87cd3c1a2509.jpg)

**Comment by wbprice** [comment]
@nameispete love it.  This is pretty similar to some of the ideas we were kicking around at hack night.

**Comment by jalbertbowden** [comment]
think i have icons but i can't find your list of headings/topics/etc.
question:
http://openhealthinspection.com/#/  
does the app url have "#"?

**Comment by qwo** [comment]
this is how frameworks like Angular and Ember handle routing so you can link in context.

This article has info about how to fix it but its a non priority. http://scotch.io/quick-tips/js/angular/pretty-urls-in-angularjs-removing-the-hashtag

This is the icon list
Education
Hospitality
Restaurant
Grocery
Government
Medical
Mobile Food
Other

**\* Edit its in this issue. https://github.com/c4hrva/open-health-inspection-app/issues/85#issuecomment-47848798

**Comment by kmcurry** [comment]
Oh. Hi! :smile:

On Fri, Jul 4, 2014 at 1:55 AM, W. Blaine Price notifications@github.com
wrote:

> @nameispete https://github.com/nameispete love it. This is pretty
> similar to some of the ideas we were kicking around at hack night.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/77#issuecomment-48011226
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by qwo** [comment]
@kmcurry agreed thats the first thing i saw, also the state of OHIO :smile_cat:

**Comment by jalbertbowden** [comment]
urs, dedicated uris, are most certainly always a priority.
not knowing that....or openly choosing against it.....uh wat?
i know it doesn't matter when its my opinion, but tbl weighed in heavily against it.
then again, he only invented the internet.

so wait...all those hashbang urls are simply because some backender coudln't figure out dynamic names/layout.
lolololololololololololol

genius.

i'll send out the icons in a few.

its way late in the game to even care at this point, its just glaringly obvious.
like the mailto protocol.

k i think we have multiple options in icons. i'll go back through and let ya'll pick

**Comment by qwo** [comment]
this was a decision angular made, you can find some of this in this discussion @jalbertbowden https://github.com/angular/angular.js/issues/4608 

Thanks about the icons, postem to this issue. *\* https://github.com/c4hrva/open-health-inspection-app/issues/85#issuecomment-47848798

**Comment by jalbertbowden** [comment]
i hope they make the decisions in their company.
you chose to use them
then chose not to implement the fixa
so thats their fault?

clearly its done....not sure where the confusion is from.

**Comment by jalbertbowden** [comment]
SJJB Maps
http://www.sjjb.co.uk/mapicons/downloads

i see all the ones except for "other" and a distinct "government"....but there's plenty to pick from.
i have the pngs, in tons of colors if you don't want to render them yourself

of note: check out the prison amentiy icons

**Comment by wbprice** [comment]
Here's my attempt at a logo based on what we've been kicking around so far.
![ohilogo2](https://cloud.githubusercontent.com/assets/2590422/3489307/cd86a1c8-0524-11e4-9a60-7e03c070b44e.png)

**Comment by nameispete** [comment]
I really like that! Kudos!

 I get that it's a plate -- I wonder if maybe by putting another circle just inside the outer "O"-- it might communicate the plate message more effectively. Still that's out-of-park for me. Great work.

**Comment by nameispete** [comment]
One more observation.... if it was flipped horzontally... it absolutely could never be seen as a "Q" ....

**Comment by wbprice** [comment]
Sounds good to me.  Also easier and cheaper than renaming the app to Qpen Health Inspection.

**Comment by qwo** [comment]
maybe if there was inner plate line, it would be easier to discern + show a bit of depth 
![search](https://cloud.githubusercontent.com/assets/3683993/3489365/9a25b562-0529-11e4-8881-01b386d3c1aa.jpg)

**Comment by wbprice** [comment]
revised full size:
![ohilogo2v2](https://cloud.githubusercontent.com/assets/2590422/3489418/f9000af4-052b-11e4-87c1-10ae323587b8.png)
title bar size:
![ohilogo2v2blue-small](https://cloud.githubusercontent.com/assets/2590422/3489424/31bfb196-052c-11e4-9876-bc85f4b76b9f.png)
plate + magnifying glass + O = triple word score.

**Comment by wbprice** [comment]
Adding logo and favicons in #107.

**Comment by aimsrandom** [comment]
Concept from one of our graphic designers at InMotion

![spoon-plate-magnifying-icon-idea](https://cloud.githubusercontent.com/assets/7144451/3500750/80286232-060e-11e4-8dba-cb03657cd8bb.jpg)

**Comment by wbprice** [comment]
Revised:
![ohilogo2v3](https://cloud.githubusercontent.com/assets/2590422/3503189/94a0f6a2-062c-11e4-85b3-1525d00f1add.png)
Small:
![ohilogo2v3small](https://cloud.githubusercontent.com/assets/2590422/3503188/94a0a6d4-062c-11e4-8797-f9f7c4cc1478.png)

**Comment by nameispete** [comment]
That's pretty cool.

**Comment by wbprice** [comment]
Updated the live site with new icons in #109
