### ISSUE TITLE
Display an icon that relates to the category of the vendor in listview.

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#85]
There are ~48 different categories in the database, so we'll want to boil them down somewhat.
- Government
- Restaurants
- Schools
- Churches

etc.

**Comment by ttavenner** [comment]
Here is the total list of vendor types in the database. Obviously these need to be grouped a bit less granularly:

{
    "0" : "Seasonal Fast Food Restaurant",
    "1" : "Fast Food Restaurant",
    "2" : "Full Service Restaurant",
    "3" : "Public Middle or High School Food Service",
    "4" : "Mobile Food Unit",
    "5" : "Private Elementary School Food Service",
    "6" : "Child Care Food Service",
    "7" : "Other Food Service",
    "8" : "Mobile food unit",
    "9" : "Public Elementary School Food Service",
    "10" : "Dept. of Juvenile Justice Food Service",
    "11" : "Carry Out Food Service Only",
    "12" : "Commissary",
    "13" : "Hotel Continental Breakfast",
    "14" : "Full Service Restaurant/Caterer",
    "15" : "Hospital Food Service",
    "16" : "Caterer",
    "17" : "State College Food Service",
    "18" : "Convenience Store Food Service",
    "19" : "Private Middle or High School Food Service",
    "20" : "Bed & Breakfast Food Service",
    "21" : "Adult Care Home Food Service",
    "22" : "Fast Food Restaurant/Caterer",
    "23" : "Adult Day Care Food Service",
    "24" : "Nursing Home Food Service",
    "25" : "Summer Food Service Program Feeding Site",
    "26" : "Jail Food Service",
    "27" : "Private College Food Service",
    "28" : "Group Home Food Service",
    "29" : "Seasonal Full Service Restaurant",
    "30" : "Summer Camp Food Service",
    "31" : "Grocery Store Food Service",
    "32" : "Public Elementry School Food Service",
    "33" : "Public Primary School Food Service",
    "34" : "Private High School Food Service",
    "35" : "State Institution Food Service",
    "36" : "Summer camp kitchen",
    "37" : "Institution",
    "38" : "Residential Child Care Institution Food Service",
    "39" : "Summer Food Service Program Kitchen",
    "40" : "Hotel continental breakfast",
    "41" : "Public school kitchen",
    "42" : "Snack Bar",
    "43" : null,
    "44" : "Bed & Breakfast",
    "45" : "Restaurant",
    "46" : "Private Elementry School Food Service",
    "47" : "Adult care home food service"
}

**Comment by wbprice** [comment]
## Proposed Condensed List:

Education
Hospitality
Restaurant
Grocery
Government
Medical
Mobile Food
Other

**Comment by qwo** [comment]
icons can be selected from 
- Glyphicons http://getbootstrap.com/components/
- Favicons http://fortawesome.github.io/Font-Awesome/
- Octicons https://octicons.github.com/

**Comment by aimsrandom** [comment]
Education:  http://fortawesome.github.io/Font-Awesome/icon/graduation-cap/

Hospitality:  http://fortawesome.github.io/Font-Awesome/icon/building/

Restaurant:  http://fortawesome.github.io/Font-Awesome/icon/cutlery/

Grocery: http://fortawesome.github.io/Font-Awesome/icon/shopping-cart/

Government:  http://fortawesome.github.io/Font-Awesome/icon/university/

Medical:  http://fortawesome.github.io/Font-Awesome/icon/plus-square/
Or, a hospital building for Medical:  http://fortawesome.github.io/Font-Awesome/icon/hospital-o/

Mobile Food:   http://fortawesome.github.io/Font-Awesome/icon/truck/

Other:  http://fortawesome.github.io/Font-Awesome/icon/spoon/

**Comment by wbprice** [comment]
resolved in #119.  Will probably be able to use this work in #99 too.
