### ISSUE TITLE
give me a cool name

### ISSUE THREAD

**Issue by qwo** [Code4HR/open-health-inspection-app#9]
inspectva.org
inspectus.org

**Comment by ttavenner** [comment]
whatseat

**Comment by jalbertbowden** [comment]
eat.me

On Mon, Feb 24, 2014 at 11:24 AM, ttavenner notifications@github.comwrote:

> whatseat
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/open-health-inspection-app/issues/9#issuecomment-35903897
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by qwo** [comment]
valives
http://www.yelp.com/healthscores

**Comment by wbprice** [comment]
- eatsafe.com
- safe-eats.com

**Comment by kmcurry** [comment]
Define my purpose.

On Mon, Feb 24, 2014 at 5:47 PM, William Blaine Price <
notifications@github.com> wrote:

> - eatsafe.com
> - safe-eats.com
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/open-health-inspection-app/issues/9#issuecomment-35949870
> .

## 

Kevin Curry
757-613-8158
Advisor, Code for America
http://brigade.codeforamerica.org

CodeAcross HRVA February 21 & 22:
http://www.codeforhamptonroads.org/codeacross

**Comment by wbprice** [comment]
Super negative but...
- redflagspecial.com
- healthcodebreakers.com
  We should celebrate restaurants that do well instead of dumping on gross places.

**Comment by wbprice** [comment]
A more creative mind than mine came up with these.
- EatHereNotThere
- Rate My Restaurant
- Health Inspector Detector
- Get the Dirty on your Dining
- (Dining) Dirty Secrets
- Secret Diner

**Comment by jalbertbowden** [comment]
eternal.five.second.ru.le

On Tue, Feb 25, 2014 at 9:41 AM, William Blaine Price <
notifications@github.com> wrote:

> More creative minds than mine came up with these.
> - EatHereNotThere
> - Rate My Restaurant
> - Health Inspector Detector
> - Get the Dirty on your Dining
> - (Dining) Dirty Secrets
> - Secret Diner
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/open-health-inspection-app/issues/9#issuecomment-36013578
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by qwo** [comment]
localdishing.com
dishOnDishes
vaplates.com/org

**Comment by wbprice** [comment]
- opendishesva.com
- cleandishesva.com

**Comment by kmcurry** [comment]
IDontHaveAPurposeYetSoICantKnowMyName.com

PlusWeDontNeedToKeepShellingOutDollarsForCleverDomainNames.com

On Tue, Feb 25, 2014 at 10:36 AM, William Blaine Price <
notifications@github.com> wrote:

> - opendishesva.com
> - cleandishesva.com
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/c4hrva/open-health-inspection-app/issues/9#issuecomment-36020013
> .

## 

Kevin Curry
757-613-8158
Advisor, Code for America
http://brigade.codeforamerica.org

CodeAcross HRVA February 21 & 22:
http://www.codeforhamptonroads.org/codeacross

**Comment by kmcurry** [comment]
eternal.five.second.ru.le is hilarious though

**Comment by BretFisher** [comment]
food.codeforhamptonroads.org
resturants.codeforhamptonroads.org

more importantly:
openinspectionapi.codeforhamptonroads.org

rememeber we have the c4hrva.us domain too.

**Comment by qwo** [comment]
yum.c4hrva.us 
clever.domains.are.fun.us

**Comment by jalbertbowden** [comment]
yes.they.are

tried to get homes.com to buy hom.es when it was available, but what do i know ;)
kevin's have me laughing...but i'm totally with bret here. basic. subdomain...or appended root. whatever. i'd so go major generic, but i think there are states using different formats right? not LIVES, but how they gather/consume the data. thats why we don't have scores, right?

**Comment by BretFisher** [comment]
As I understand it: other then LIVES there is no standard. every city,
county, state is different, some score, some don't, hence the CfA + SF +
NYC + Yelp = LIVES effort

**Comment by jalbertbowden** [comment]
no.one.gets.out.a.lives

**Comment by CNick** [comment]
healthcoderank.com (.net, .org, & .info also available)
healthcode.info
Could also add va to the beginning of either of those.

And.... because I can't help but be sarcastic: noratsinmysoup.com

**Comment by wbprice** [comment]
Maybe after this gets more exposure at NDoCH someone will come up with a cool name for us.

**Comment by wbprice** [comment]
I bought the domain openhealthinspection.com.  We might be able to get the domain refunded by InMotion,  but heck, it's $15 so whatever.

**Comment by qwo** [comment]
i think this is closed?
