### ISSUE TITLE
Introduction Modal

### ISSUE THREAD

**Issue by wbprice** [Code4HR/open-health-inspection-app#95]
Introduction to app, how to use, where to send feedback, etc.

**Comment by nameispete** [comment]
I'll start wordsmithing something.

**Comment by nameispete** [comment]
## First Blush - User Education - opening screen

Learn more about where you eat! Click a pin and "Get Report" and you will have the latest publicly available health inspection report for that restaurant. There are two modes. List and Map. List takes you to all of the places within five miles of your location. Map takes you all around Virginia. Be sure to zoom into the map to see specific reports. This app provides current reports on over 26,000 places to eat throughout Virginia.

**Comment by qwo** [comment]
had to check up on the scraper db and run a query

```
//count all the records in the database
db.va.count();
//26595
```

so there are 26595 food vendors in the state of virginia, if we want to narrow it down to Hampton Roads or even smaller Norfolk i can grab those numbers too

**Comment by nameispete** [comment]
@stanzheng  Thank you. Integrated your results into "first blush user education" ----

**Comment by wbprice** [comment]
Used the above as the basis for what was put into the modal in #106
