### ISSUE TITLE
Add feedback button(s) and associated assets

### ISSUE THREAD

**Issue by nameispete** [Code4HR/open-health-inspection-app#96]
We should add a feedback mechanism. 

The most basic option is a simple email link. It's a nice one-size-fits-all and we can use a javascript that puts a subject into the email for quick filtering. 

I am not sure how we pluck tasks from the stack...... I can set up a gmail account for this app that forwards to everyone involved.

**Comment by wbprice** [comment]
I set up a openhealthinspection@gmail.com email address last night at hack night, so no worries.

**Comment by nameispete** [comment]
Awesome... 

so I know we talked about a dedicated Twitter, but unless you guys think otherwise.. an email with a predefined subject "FEEDBACK on OpenHealthInspection" works really well and allows nice multiple forwarding through gmail and does not require monitoring of the specific twitter account.

**Comment by qwo** [comment]
sounds like a plan!

**Comment by jalbertbowden** [comment]
thats actually a no-no in ux 101.
not picking, just saying

**Comment by qwo** [comment]
what do you suggest as an alternative @jalbertbowden? 

*\* or what is the recommended mechanism

**Comment by jalbertbowden** [comment]
a form on the page that does the same thing, except it doesn't take them away from where they are, and it doesn't need another user-agent to work.
or open another tab.

**Comment by wbprice** [comment]
@jalbertbowden We did this for hrtb.us.  I'm fine with building a contact form that forwards to openhealthinspection@gmail.com.

**Comment by kmcurry** [comment]
Scanning thread on feedback...not seeing UserVoice...

It's what we use for HRTB.us.

On Thu, Jul 3, 2014 at 10:01 AM, W. Blaine Price notifications@github.com
wrote:

> @jalbertbowden https://github.com/jalbertbowden We did this for hrtb.us.
> I'm fine with building a contact form that forwards to
> openhealthinspection@gmail.com.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/96#issuecomment-47933212
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by wbprice** [comment]
@kmcurry is it still the case that only @BretFisher has access to UserVoice feedback? Are we able to add a second project and leave that under one account?

**Comment by kmcurry** [comment]
Make a new account specifically for the app. Use that gmail you created as
the user, generate a 128+ bit key and put it in a safe place. @BretFisher?

On Thu, Jul 3, 2014 at 11:00 AM, W. Blaine Price notifications@github.com
wrote:

> @kmcurry https://github.com/kmcurry is it still the case where only
> @BretFisher https://github.com/BretFisher has access to UserVoice
> feedback? Are we able to add a second project and leave that under one
> account?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/96#issuecomment-47940889
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by BretFisher** [comment]
so we could have a group account for UserVoice but that's against their EULA. Also the way UV works is you create a new project (site) for each app.  Unless we use the FAQ + Feedback features I think UV is overkill. What we need is a opensource web app that lets us quickly throw a button/link on any web app, which gives them a simple form, and tracks responses, email notifications, etc.

**Comment by BretFisher** [comment]
no idea what @kmcurry is talking about in his last post. "128+ bit key"?

**Comment by BretFisher** [comment]
http://stackoverflow.com/questions/1576935/open-source-alternative-to-uservoice-or-get-satisfaction

**Comment by BretFisher** [comment]
dated, but http://mashable.com/2011/03/06/user-feedback-apps/

**Comment by nameispete** [comment]
Along with Albert-- I am not "picking"-- but keep in mind that we are looking at press release (and hopefully many new users) in 7 days.... 

We have a workable, rapid solution (albeit not elegant) in the form of an email link that we **know** works and everyone and their grandmother knows how to use....even if it spawns a new user agent....  

As for the larger discussion, it does seem that we need to find a common set of rules for feedback mechanisms across all the upcoming and legacy apps/website.. I am merely suggesting that this may or may not be the best moment in time specific to this particular launch.

**Comment by qwo** [comment]
you raise a good point @nameispete, we subscribe to x-many services but maybe we should standardize at least how users can give feedback for @c4hrva apps for consistency and easier to manage/implement.

**Comment by BretFisher** [comment]
Agree with all. I think of email link as better then nothing, but we've had feedback that indicates the email link method is inferior to a modal that lets them type in app and submit.  Maybe that's the next "brigade helping brigade" app: a .js modal form that sends feedback to a google sheet or similar as a very-low-tech way to get feedback from small apps that don't warrant the UV approach.

**Comment by jalbertbowden** [comment]
dont think huge when i say form....
it would look exactly how ya'll are thinking/were thinking.
but when its clicked, you stay where you are....

you can target different user agents for different things...

just like how i pointed out using tel: protocol is fun for mobile, but not
on desktop.

ps va beach has that code in production

On Thu, Jul 3, 2014 at 1:18 PM, Bret Fisher notifications@github.com
wrote:

> Agree with all. I think of email link as better then nothing, but we've
> had feedback that indicates the email link method is inferior to a modal
> that lets them type in app and submit. Maybe that's the next "brigade
> helping brigade" app: a .js modal form that sends feedback to a google
> sheet or similar as a very-low-tech way to get feedback from small apps
> that don't warrant the UV approach.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/96#issuecomment-47958642
> .

## 

J. Albert Bowden II

jalbertbowden@gmail.com

http://bowdenweb.com/

**Comment by kmcurry** [comment]
For generating random pwd. Nvm.

On Thu, Jul 3, 2014 at 12:17 PM, Bret Fisher notifications@github.com
wrote:

> no idea what @kmcurry https://github.com/kmcurry is talking about in
> his last post. "128+ bit key"?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/96#issuecomment-47951297
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by nameispete** [comment]
To finalize. We are going with a simple email link for the OHI release. We will expand the topic and develop easy-to-implement standards and mechanisms for feedback for this app and future ones at a later date. Is this about right?

**Comment by wbprice** [comment]
In the first pass I'll include the openhealthinspection@gmail.com address in the introduction modal.  After addressing the three or so other critical issues, I'll build an in-app form.

**Comment by nameispete** [comment]
honestly, @wbprice -- if we can have an intro screen, we can explain how it works as well as have a link to feedback. Just need an introductory single page (html)? prior to application launch. 

1) Be able to switch between list and map
2) Have geocenter on relocation

We are gold for July 10.
