### ISSUE TITLE
July 10th target - Press release to Norfolk influencers in media. 

### ISSUE THREAD

**Issue by nameispete** [Code4HR/open-health-inspection-app#97]
Are there examples of press releases that we've done in the past?

**Comment by qwo** [comment]
Here is the link to the @c4hrva google drive.

for the hrtb.us release there were some written. https://drive.google.com/#folders/0BzQFSkq0ERZOcms4c0x2YWJIejQ 

for national events we had like CodeAcross and National Day there are also some press releases in their respective folders 

https://drive.google.com/#folders/0B_WC8QOgiwjzeDBPRkM2UW05ZjA

**Comment by qwo** [comment]
I'd be happy to list the link of Norfolk Influencers  below here.. lemme start compiling 
- AltDaily 
  - Jesse Scaccia  jesse@altdaily.com
- VeerMagazine
  - Jeff Maisey jeffmaisey@cox.net
- Virginia Pilot
  -  Patrick Wilson patrick.wilson@pilotonline.com
  -  Ana Upton ana.upton@pilotonline.com
  - tips@pilotonline.com
- WTKR 
  - desk@wtkr.com
  - Newsroom@wtkr.com
- Wavy 10 
  -     Newsdesk@wavy.com
- WVEC 13
  - newstips@wvec.com

**Comment by kmcurry** [comment]
:thumbsup:

On Thu, Jul 3, 2014 at 9:48 AM, Stanley Zheng notifications@github.com
wrote:

> Here is the link to the @c4hrva https://github.com/c4hrva google drive.
> 
> for the hrtb.us release there were some written.
> https://drive.google.com/#folders/0BzQFSkq0ERZOcms4c0x2YWJIejQ
> 
> for national events we had like CodeAcross and National Day there are also
> some press releases in their respective folders
> 
> https://drive.google.com/#folders/0B_WC8QOgiwjzeDBPRkM2UW05ZjA
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/97#issuecomment-47931473
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by qwo** [comment]
@kmcurry have more contacts to contribute?

**Comment by kmcurry** [comment]
Not off hand but search all the locals for their food contributors and
editors. Add them.

If we write a piece for AltDaily it will be published almost certainly.

On Thu, Jul 3, 2014 at 10:40 AM, Stanley Zheng notifications@github.com
wrote:

> @kmcurry https://github.com/kmcurry have more contacts to contribute?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/97#issuecomment-47938074
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by nameispete** [comment]
---

"what's inside their kitchen?"
"How clean is their kitchen?
Openhealthinspection.com launches in anticipation of  Norfolk Restaurant Week
 timely restaurant health reports for free from your phone or computer

With Norfolk Restaurant week coming up this Monday, July 13th, folks around the area are wondering not only how tasty a restaurant’s food is, but also how clean the restaurant's kitchen is. OpenHealthInspection.com answers that question by providing a free easy-to-use, map-enabled web app. you can visit on your phone or computer that shows the latest health inspection reports directly from the Virginia Department of Health. 

“Our goal was to make existing information easier to find so that restaurant goes can make a more informed decisions. ”, says Tommy Tavenner, a co-developer of the site. “OHI provides plain English descriptions for any health code violations  as well as whether it has been corrected. "

When accessed from a phone OHI automatically provides a list of all restaurants within a five mile radius. With a simple touch, you can access the latest health inspection report for a specific restaurant. You can also "travel" around the map to find the latest publicly available reports for every restaurant throughout the entire state of Virginia. 

OpenHealthInspection.com was created entirely by volunteers working with Code for Hampton Roads. The information presented in the application is gathered from HealthSpace.com and the Virginia  Department of Health.

About Code for Hampton Roads
Code for Hampton Roads is a volunteer organization dedicated to civic innovation for southeastern Virginia. Members of Code for Hampton Roads belong to a national network of Code for America volunteers who help their local governments and community service organizations better utilize technology. To find out more about Code for Hampton Roads visit: http://codeforhamptonroads.org. To find out more about Code for America visit: http://codeforamerica.org

**Comment by qwo** [comment]
nice @nameispete this reads like a real professional article.

C4HRVA has been featured in print and media before so maybe some inspiration from that

http://hamptonroads.com/2013/10/volunteers-build-app-track-hrt-buses-real-time 
http://hamptonroads.com/2013/05/hackers-put-white-hats-civic-duty-norfolk

**Comment by nameispete** [comment]
Last call for comments on PRESS RELEASE-- it will go out around 10:30am

Here is a link to the PDF 

https://drive.google.com/#folders/0B3yyYdD_lUkrVFQtSmUwWkJ2OEE

**Comment by kmcurry** [comment]
Looks good!

On Wednesday, July 9, 2014, Peter Tyrrell notifications@github.com wrote:

> Last call for comments on PRESS RELEASE-- it will go out around 10:30am
> 
> Here is a link to the PDF
> 
> https://drive.google.com/#folders/0B3yyYdD_lUkrVFQtSmUwWkJ2OEE
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/c4hrva/open-health-inspection-app/issues/97#issuecomment-48552857
> .

## 

Kevin Curry
Virginia Beach, VA
http://www.linkedin.com/in/kevincurry

**Comment by nameispete** [comment]
Sent them out... will be sending more!! Congratulations! Nice work on this application!
