### ISSUE TITLE
moving around the map 

### ISSUE THREAD

**Issue by nameispete** [Code4HR/open-health-inspection-app#98]
We absolutely need means to refresh restaurants to geocenter of the map. It's okay if its a button.

For me, when I check out the site from my PC, it puts my location several miles southeast of where I am. I am in central VB-- it gives me southeastern VB. There is no way to explore restaurants anywhere except the initial location. Or if there is ... it is not clear. 

@wbprice @stanzheng I know that we talked about this yesterday and it seemed like a known issue, but I could not locate it in the open issues area. If I have duplicated it, feel free to delete this message.

**Comment by qwo** [comment]
Hi @nameispete that sounds like your browser and your ISP, how most apps utilize 'use my location' is handled is by the browser and the ISP i believe.

We aren't doing anything special in that regard and is handled differently I believe by browser and where you're connection. 

see 
http://html5demos.com/geo
http://www.sitepoint.com/html5-geolocation/

**Comment by nameispete** [comment]
@stanzheng, thanks for the links/info. Good stuff. 

 I am on Verizon FIOS and they are putting my location toward Rudee inslet. No way for me to see restaurants not near there.

**Comment by qwo** [comment]
yeah for geo location, sometimes they place me in hampton/virginia for cox users. Im not an expert but usually wifi data provides the most accurate results with geo location and mobile data is a bit spotty.

**Comment by qwo** [comment]
the way to solve this is to take an uber or lyft way of creating a device/map center, and that being the source of truth for the 'geolocation center' of where a user is or where they're interested in. That is intricate knowledge of the google maps API that im not sure @wbprice about

**Comment by jalbertbowden** [comment]
on desktop you are pinged to the server isp....so in va beach we are all @ ocean front.
mobile provides level(s) of granularity.
the solution(s), again are to feature detect who and what you are serving up.
gmaps provides all this functionality...i've done it before....

**Comment by wbprice** [comment]
Partially addressed in #100, in which I've placed a pin at the center of the map.  To get new results, position the pin, click update.  Consistent with behavior of Lyft/Uber and Google Maps.

**Comment by wbprice** [comment]
The second half of this is going to be to keep track of how far away the map center is from the last geosearch coordinates, and then make another geosearch call on the dragend event when more than about a half mile away.  Get ready for performance issues.

**Comment by wbprice** [comment]
So the pseudocode for this:
1. When map center is x meters away from previous call:
2. Make a second geosearch call, and add the results to the end of an array.
3. Sort that array by distance from my current location
4. Use it to draw appropriate map pins 
5. Use it to populate the list
6. Enforce a maximum array size and clear out old results as new ones arrive.

Will need to account for zoom level at some point too.
